name: Build Vaultwarden
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Clone Github Repo
          run: |
            git clone --depth 1 https://github.com/dani-garcia/vaultwarden
        - name: Build Vaultwarden
          run: |
           cd vaultwarden
           (Get-Content Cargo.toml) -replace '\[dependencies\]', "[dependencies]`nmysqlclient-sys = { version = '0.5', features = ['bundled'], optional = true }" | Set-Content Cargo.toml
           (Get-Content Cargo.toml) -replace 'openssl\s*=\s*"([\d\.]+)"', 'openssl = { version = "$1", features = ["vendored"] }' | Set-Content Cargo.toml
           cargo build --release --features sqlite,mysql
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4
          with:
            path: vaultwarden/target/release




            
