name: Build Vaultwarden
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Clone Github Repo
          run: |
            git clone --depth 1 https://https://github.com/dani-garcia/vaultwarden
        - name: setup mysql, openssl and postgresql
          run: |
                choco install mysql
                choco install openssl
                choco install postgresql
        - name: build
          run: |
           cd vaultwarden
           cargo build --release --features sqlite,mysql
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4
          with:
            path: vaultwarden/target/release




            
